"""database best practices - indexes, constraints, cascades

Revision ID: 017aafa19e8a
Revises: 4b81d9ac13a6
Create Date: 2025-12-19 01:08:04.217275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017aafa19e8a'
down_revision = '4b81d9ac13a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_deal', schema=None) as batch_op:
        batch_op.create_index('ix_active_deal_proposal', ['proposal_id'], unique=False)
        batch_op.create_index('ix_active_deal_status', ['status'], unique=False)
        batch_op.create_unique_constraint(None, ['proposal_id'])
        batch_op.drop_constraint(batch_op.f('active_deal_proposal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'deal_proposal', ['proposal_id'], ['proposal_id'], ondelete='CASCADE')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_index('ix_company_join_code', ['join_code'], unique=False)
        batch_op.create_index('ix_company_name', ['name'], unique=False)

    with op.batch_alter_table('company_join_request', schema=None) as batch_op:
        batch_op.create_index('ix_company_join_request_company', ['company_id'], unique=False)
        batch_op.create_index('ix_company_join_request_user', ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_company_join_request_company_user', ['company_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('company_join_request_company_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('company_join_request_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['company_id'], ondelete='CASCADE')

    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.create_index('ix_company_member_company', ['company_id'], unique=False)
        batch_op.create_index('ix_company_member_user', ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_company_member_company_user', ['company_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('company_member_company_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('company_member_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['company_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('deal_proposal', schema=None) as batch_op:
        batch_op.create_index('ix_deal_proposal_from_company', ['from_company_id'], unique=False)
        batch_op.create_index('ix_deal_proposal_status', ['status'], unique=False)
        batch_op.create_index('ix_deal_proposal_to_company', ['to_company_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('deal_proposal_to_company_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('deal_proposal_from_service_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('deal_proposal_to_service_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('deal_proposal_from_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['to_company_id'], ['company_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'service', ['from_service_id'], ['service_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'company', ['from_company_id'], ['company_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'service', ['to_service_id'], ['service_id'], ondelete='CASCADE')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index('ix_review_deal', ['deal_id'], unique=False)
        batch_op.create_index('ix_review_reviewed_company', ['reviewed_company_id'], unique=False)
        batch_op.create_index('ix_review_reviewed_service', ['reviewed_service_id'], unique=False)
        batch_op.create_index('ix_review_reviewer', ['reviewer_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('review_reviewed_company_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('review_reviewed_service_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('review_reviewer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('review_deal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reviewer_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'active_deal', ['deal_id'], ['active_deal_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'service', ['reviewed_service_id'], ['service_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'company', ['reviewed_company_id'], ['company_id'], ondelete='SET NULL')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index('ix_service_categories', ['categories'], unique=False)
        batch_op.create_index('ix_service_company', ['company_id'], unique=False)
        batch_op.create_index('ix_service_is_active', ['is_active'], unique=False)
        batch_op.drop_constraint(batch_op.f('service_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['company_id'], ondelete='CASCADE')

    with op.batch_alter_table('service_view_event', schema=None) as batch_op:
        batch_op.create_index('ix_service_view_event_service', ['service_id'], unique=False)
        batch_op.create_index('ix_service_view_event_viewed_at', ['viewed_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('service_view_event_service_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['service_id'], ondelete='CASCADE')

    with op.batch_alter_table('trade_request', schema=None) as batch_op:
        batch_op.create_index('ix_trade_request_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_trade_request_requested_service', ['requested_service_id'], unique=False)
        batch_op.create_index('ix_trade_request_requesting_company', ['requesting_company_id'], unique=False)
        batch_op.create_index('ix_trade_request_status', ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('trade_request_requesting_company_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('trade_request_requested_service_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'service', ['requested_service_id'], ['service_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'company', ['requesting_company_id'], ['company_id'], ondelete='CASCADE')

    with op.batch_alter_table('tradeflow_view', schema=None) as batch_op:
        batch_op.create_index('ix_tradeflow_view_company', ['company_id'], unique=False)
        batch_op.create_index('ix_tradeflow_view_user', ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_tradeflow_view_company_user_section', ['company_id', 'user_id', 'section'])
        batch_op.drop_constraint(batch_op.f('tradeflow_view_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tradeflow_view_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['company_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_user_username')
        batch_op.drop_index('ix_user_email')
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('tradeflow_view', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tradeflow_view_company_id_fkey'), 'company', ['company_id'], ['company_id'])
        batch_op.create_foreign_key(batch_op.f('tradeflow_view_user_id_fkey'), 'user', ['user_id'], ['user_id'])
        batch_op.drop_constraint('uq_tradeflow_view_company_user_section', type_='unique')
        batch_op.drop_index('ix_tradeflow_view_user')
        batch_op.drop_index('ix_tradeflow_view_company')

    with op.batch_alter_table('trade_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trade_request_requested_service_id_fkey'), 'service', ['requested_service_id'], ['service_id'])
        batch_op.create_foreign_key(batch_op.f('trade_request_requesting_company_id_fkey'), 'company', ['requesting_company_id'], ['company_id'])
        batch_op.drop_index('ix_trade_request_status')
        batch_op.drop_index('ix_trade_request_requesting_company')
        batch_op.drop_index('ix_trade_request_requested_service')
        batch_op.drop_index('ix_trade_request_expires_at')

    with op.batch_alter_table('service_view_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_view_event_service_id_fkey'), 'service', ['service_id'], ['service_id'])
        batch_op.drop_index('ix_service_view_event_viewed_at')
        batch_op.drop_index('ix_service_view_event_service')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_company_id_fkey'), 'company', ['company_id'], ['company_id'])
        batch_op.drop_index('ix_service_is_active')
        batch_op.drop_index('ix_service_company')
        batch_op.drop_index('ix_service_categories')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_deal_id_fkey'), 'active_deal', ['deal_id'], ['active_deal_id'])
        batch_op.create_foreign_key(batch_op.f('review_reviewer_id_fkey'), 'user', ['reviewer_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('review_reviewed_service_id_fkey'), 'service', ['reviewed_service_id'], ['service_id'])
        batch_op.create_foreign_key(batch_op.f('review_reviewed_company_id_fkey'), 'company', ['reviewed_company_id'], ['company_id'])
        batch_op.drop_index('ix_review_reviewer')
        batch_op.drop_index('ix_review_reviewed_service')
        batch_op.drop_index('ix_review_reviewed_company')
        batch_op.drop_index('ix_review_deal')

    with op.batch_alter_table('deal_proposal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('deal_proposal_from_company_id_fkey'), 'company', ['from_company_id'], ['company_id'])
        batch_op.create_foreign_key(batch_op.f('deal_proposal_to_service_id_fkey'), 'service', ['to_service_id'], ['service_id'])
        batch_op.create_foreign_key(batch_op.f('deal_proposal_from_service_id_fkey'), 'service', ['from_service_id'], ['service_id'])
        batch_op.create_foreign_key(batch_op.f('deal_proposal_to_company_id_fkey'), 'company', ['to_company_id'], ['company_id'])
        batch_op.drop_index('ix_deal_proposal_to_company')
        batch_op.drop_index('ix_deal_proposal_status')
        batch_op.drop_index('ix_deal_proposal_from_company')

    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('company_member_user_id_fkey'), 'user', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('company_member_company_id_fkey'), 'company', ['company_id'], ['company_id'])
        batch_op.drop_constraint('uq_company_member_company_user', type_='unique')
        batch_op.drop_index('ix_company_member_user')
        batch_op.drop_index('ix_company_member_company')

    with op.batch_alter_table('company_join_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('company_join_request_user_id_fkey'), 'user', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('company_join_request_company_id_fkey'), 'company', ['company_id'], ['company_id'])
        batch_op.drop_constraint('uq_company_join_request_company_user', type_='unique')
        batch_op.drop_index('ix_company_join_request_user')
        batch_op.drop_index('ix_company_join_request_company')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('ix_company_name')
        batch_op.drop_index('ix_company_join_code')
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('active_deal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('active_deal_proposal_id_fkey'), 'deal_proposal', ['proposal_id'], ['proposal_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_active_deal_status')
        batch_op.drop_index('ix_active_deal_proposal')

    # ### end Alembic commands ###
