"""Remove unused columns from User and Service

Revision ID: 0809688cee27
Revises: 90c24b5ed26b
Create Date: 2025-12-18 14:23:44.551756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0809688cee27'
down_revision = '90c24b5ed26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('value_estimate')
        batch_op.drop_column('availability')
        batch_op.drop_column('status')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('job_description')
        batch_op.drop_column('location')
        batch_op.drop_column('role')
        batch_op.drop_column('verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('value_estimate', sa.NUMERIC(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
