"""Remove unused tables: service_categories, service_interest, message, deliverable

Revision ID: 188bacbd9f1e
Revises: b338d889930e
Create Date: 2025-12-14 00:35:44.383707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '188bacbd9f1e'
down_revision = 'b338d889930e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_interest')
    op.drop_table('message')
    op.drop_table('deliverable')
    op.drop_table('service_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], name=op.f('service_categories_service_id_fkey')),
    sa.PrimaryKeyConstraint('service_id', 'category_name', name=op.f('service_categories_pkey'))
    )
    op.create_table('deliverable',
    sa.Column('deliverable_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('active_deal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['active_deal_id'], ['active_deal.active_deal_id'], name=op.f('deliverable_active_deal_id_fkey')),
    sa.ForeignKeyConstraint(['from_company_id'], ['company.company_id'], name=op.f('deliverable_from_company_id_fkey')),
    sa.PrimaryKeyConstraint('deliverable_id', name=op.f('deliverable_pkey'))
    )
    op.create_table('message',
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('proposal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_company_id'], ['company.company_id'], name=op.f('message_from_company_id_fkey')),
    sa.ForeignKeyConstraint(['proposal_id'], ['deal_proposal.proposal_id'], name=op.f('message_proposal_id_fkey')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('message_pkey'))
    )
    op.create_table('service_interest',
    sa.Column('interest_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('offering_service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], name=op.f('service_interest_company_id_fkey')),
    sa.ForeignKeyConstraint(['offering_service_id'], ['service.service_id'], name=op.f('service_interest_offering_service_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], name=op.f('service_interest_service_id_fkey')),
    sa.PrimaryKeyConstraint('interest_id', name=op.f('service_interest_pkey'))
    )
    # ### end Alembic commands ###
