"""add reviewed_service_id to review

Revision ID: 1b29f92f8786
Revises: 8a16d53686dc
Create Date: 2025-12-09 05:19:14.980571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b29f92f8786'
down_revision = '8a16d53686dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_service_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'service', ['reviewed_service_id'], ['service_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewed_service_id')

    # ### end Alembic commands ###
