"""{job description veranderd van plek} - {Ruben}

Revision ID: 1c4fcd02d779
Revises: 2b088cb728da
Create Date: 2025-11-24 12:13:45.648061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4fcd02d779'
down_revision = '2b088cb728da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###
