"""{wat je deed} - {je naam}

Revision ID: 1de6cc5141ba
Revises: 9f8c9e7d6c5b
Create Date: 2025-12-11 18:46:57.693995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1de6cc5141ba'
down_revision = '9f8c9e7d6c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    op.drop_table('barterdeal')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('barter_coins')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('barter_coins_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barter_coins_cost', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barter_coins', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    op.create_table('barterdeal',
    sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_a_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_b_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ratio_a_to_b', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_a_id'], ['service.service_id'], name='barterdeal_service_a_id_fkey'),
    sa.ForeignKeyConstraint(['service_b_id'], ['service.service_id'], name='barterdeal_service_b_id_fkey'),
    sa.PrimaryKeyConstraint('deal_id', name='barterdeal_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('contract',
    sa.Column('contract_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('signed_by_initiator', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('signed_by_counterparty', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('signed_at_initiator', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('signed_at_counterparty', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['barterdeal.deal_id'], name=op.f('contract_deal_id_fkey')),
    sa.PrimaryKeyConstraint('contract_id', name=op.f('contract_pkey'))
    )
    # ### end Alembic commands ###
