"""{2 ijen weg uit user (had daarnet vergeten saven)} - {Ruben}

Revision ID: 2b088cb728da
Revises: b0fa25a75373
Create Date: 2025-11-24 12:07:06.487683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b088cb728da'
down_revision = 'b0fa25a75373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('company_name')
        batch_op.drop_column('platform_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_role', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
