"""added is_admin to CompanyMember

Revision ID: 37509ab8527d
Revises: 1c4fcd02d779
Create Date: 2025-11-25 11:37:13.142756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37509ab8527d'
down_revision = '1c4fcd02d779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
