"""Initial migration - Eli

Revision ID: 3e1d5d501004
Revises: 
Create Date: 2025-12-08 20:00:38.140738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1d5d501004'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliverable', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliverable', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
