"""Add TradeflowView table for notification tracking

Revision ID: 44cf201e3198
Revises: 1de6cc5141ba
Create Date: 2025-12-13 23:50:51.792840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cf201e3198'
down_revision = '1de6cc5141ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradeflow_view',
    sa.Column('view_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('view_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tradeflow_view')
    # ### end Alembic commands ###
