"""add location and job_description to User model

Revision ID: 4b81d9ac13a6
Revises: 0809688cee27
Create Date: 2025-12-19 00:22:45.038317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b81d9ac13a6'
down_revision = '0809688cee27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('job_description')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
