"""add TradeRequest model for tradeflow system

Revision ID: 8a16d53686dc
Revises: beb9453c8f51
Create Date: 2025-12-09 03:10:25.248742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a16d53686dc'
down_revision = 'beb9453c8f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_request',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('requesting_company_id', sa.UUID(), nullable=False),
    sa.Column('requested_service_id', sa.UUID(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['requesting_company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_request')
    # ### end Alembic commands ###
