"""Add category and website to Company - Eline

Revision ID: 90c24b5ed26b
Revises: 375e52d046da
Create Date: 2025-12-17 15:43:37.481351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c24b5ed26b'
down_revision = '375e52d046da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
