"""Remove barter coins - Eli

Revision ID: 9f8c9e7d6c5b
Revises: 3e1d5d501004
Create Date: 2025-12-11 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8c9e7d6c5b'
down_revision = '1b29f92f8786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('barter_coins')

    with op.batch_alter_table('deal_proposal', schema=None) as batch_op:
        batch_op.drop_column('barter_coins_offered')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('barter_coins_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barter_coins_cost', sa.INTEGER(), nullable=False, server_default='0'))

    with op.batch_alter_table('deal_proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barter_coins_offered', sa.INTEGER(), nullable=False, server_default='0'))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barter_coins', sa.INTEGER(), nullable=False, server_default='0'))

    # ### end Alembic commands ###
