"""added job_description to user

Revision ID: a2d8f3b4c5de
Revises: fbbf165fd90f
Create Date: 2025-11-25 20:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d8f3b4c5de'
down_revision = 'fbbf165fd90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # make add_column idempotent in case the column already exists on DB
    op.execute("ALTER TABLE \"user\" ADD COLUMN IF NOT EXISTS job_description TEXT")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # drop only if exists (safe downgrade)
    op.execute("ALTER TABLE \"user\" DROP COLUMN IF EXISTS job_description")

    # ### end Alembic commands ###
