"""change barter coins default to 0 and update review to reference active_deal - eli

Revision ID: ab0535cdf413
Revises: df09c475261a
Create Date: 2025-11-26 01:27:31.229061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0535cdf413'
down_revision = 'df09c475261a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('review_deal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'active_deal', ['deal_id'], ['active_deal_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_deal_id_fkey'), 'barterdeal', ['deal_id'], ['deal_id'])

    # ### end Alembic commands ###
