"""{company name en platform role verwijderd} - {Ruben}

Revision ID: b0fa25a75373
Revises: 
Create Date: 2025-11-24 12:04:28.196193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0fa25a75373'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barterdeal', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('proposed', 'accepted', 'in_progress', 'delivered', 'completed', 'cancelled', name='deal_status'),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'proposed'::deal_status"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('barterdeal_services_idx'))
        batch_op.drop_constraint(batch_op.f('barterdeal_service_a_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('barterdeal_service_b_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'service', ['service_a_id'], ['service_id'])
        batch_op.create_foreign_key(None, 'service', ['service_b_id'], ['service_id'])
        batch_op.drop_table_comment(
        existing_comment='Represents a barter agreement between two companies exchanging services, users act as company representatives'
    )

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('company_company_id_fkey'), type_='foreignkey')
        batch_op.drop_table_comment(
        existing_comment='represents a company/organisation on the service2service platform.'
    )

    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('company_member_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['company_id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])
        batch_op.drop_table_comment(
        existing_comment='Connects users to companies and defines their role within the company'
    )

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('draft', 'pending', 'active', 'completed', 'void', name='contract_status'),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::contract_status"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('contract_deal_id_idx'))
        batch_op.drop_constraint(batch_op.f('contract_deal_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('contract_deal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'barterdeal', ['deal_id'], ['deal_id'])
        batch_op.drop_table_comment(
        existing_comment='Contract record linked to a deal'
    )

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('reviewer_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('review_deal_idx'))
        batch_op.drop_constraint(batch_op.f('review_deal_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('review_reviewer_id_fkey1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('review_reviewed_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reviewer_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'barterdeal', ['deal_id'], ['deal_id'])
        batch_op.create_foreign_key(None, 'company', ['reviewed_company_id'], ['company_id'])
        batch_op.drop_table_comment(
        existing_comment='Review linked to a deal; written by a user, directed at a company.'
    )

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('active', 'paused', 'archived', name='service_status'),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::service_status"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('service_user_id_idx'))
        batch_op.drop_constraint(batch_op.f('service_service_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['company_id'])
        batch_op.drop_table_comment(
        existing_comment='Represents a service offered by a company for barter deals.'
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('profile_email_uidx'))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_table_comment(
        existing_comment='Stores additional profile information for each authenticated user from Supabase Auth'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Stores additional profile information for each authenticated user from Supabase Auth',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('profile_email_uidx'), [sa.literal_column('lower(email)')], unique=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Represents a service offered by a company for barter deals.',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_service_id_fkey'), 'company', ['service_id'], ['company_id'])
        batch_op.create_index(batch_op.f('service_user_id_idx'), ['company_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('active', 'paused', 'archived', name='service_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::service_status"))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Review linked to a deal; written by a user, directed at a company.',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_reviewed_company_id_fkey'), 'company', ['reviewed_company_id'], ['company_id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('review_reviewer_id_fkey1'), 'users', ['reviewer_id'], ['id'], referent_schema='auth', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('review_deal_id_fkey'), 'barterdeal', ['deal_id'], ['deal_id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('review_deal_idx'), ['deal_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('reviewer_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Contract record linked to a deal',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('contract_deal_id_fkey'), 'barterdeal', ['deal_id'], ['deal_id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('contract_deal_id_key'), ['deal_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('contract_deal_id_idx'), ['deal_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('draft', 'pending', 'active', 'completed', 'void', name='contract_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::contract_status"))

    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Connects users to companies and defines their role within the company',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('company_member_company_id_fkey'), 'company', ['company_id'], ['company_id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('member_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_table_comment(
        'represents a company/organisation on the service2service platform.',
        existing_comment=None
    )
        batch_op.create_foreign_key(batch_op.f('company_company_id_fkey'), 'user', ['company_id'], ['user_id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('barterdeal', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Represents a barter agreement between two companies exchanging services, users act as company representatives',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('barterdeal_service_b_id_fkey'), 'service', ['service_b_id'], ['service_id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('barterdeal_service_a_id_fkey'), 'service', ['service_a_id'], ['service_id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('barterdeal_services_idx'), ['service_a_id', 'service_b_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('proposed', 'accepted', 'in_progress', 'delivered', 'completed', 'cancelled', name='deal_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'proposed'::deal_status"))

    # ### end Alembic commands ###
