"""Add archived_at to TradeRequest

Revision ID: b338d889930e
Revises: 44cf201e3198
Create Date: 2025-12-14 00:15:27.741110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b338d889930e'
down_revision = '44cf201e3198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_request', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
