"""{wat je deed} - {je naam}

Revision ID: b8eaebce5836
Revises: c3f7e2b1a988
Create Date: 2025-11-25 20:26:32.994543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8eaebce5836'
down_revision = 'c3f7e2b1a988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('platform_role')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('platform_role', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
