"""{wat je deed} - {ruben}

Revision ID: bab72457ee18
Revises: fbbf165fd90f
Create Date: 2025-11-25 12:36:56.396581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bab72457ee18'
down_revision = 'fbbf165fd90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('platform_role', sa.Text(), nullable=True))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_column('platform_role')
        batch_op.drop_column('company_name')
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###
