"""Remove estimated_time_min field from Service model

Revision ID: beb9453c8f51
Revises: 3e1d5d501004
Create Date: 2025-12-09 01:19:02.794658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb9453c8f51'
down_revision = '3e1d5d501004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliverable', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('estimated_time_min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time_min', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('deliverable', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
