"""add service trading system with interests, proposals, and active deals

Revision ID: df09c475261a
Revises: ee7149e880f0
Create Date: 2025-11-26 00:47:11.414761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df09c475261a'
down_revision = 'ee7149e880f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_proposal',
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('from_company_id', sa.UUID(), nullable=False),
    sa.Column('to_company_id', sa.UUID(), nullable=False),
    sa.Column('from_service_id', sa.UUID(), nullable=False),
    sa.Column('to_service_id', sa.UUID(), nullable=False),
    sa.Column('barter_coins_offered', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['from_service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['to_company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['to_service_id'], ['service.service_id'], ),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_table('service_categories',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.PrimaryKeyConstraint('service_id', 'category_name')
    )
    op.create_table('service_interest',
    sa.Column('interest_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('interest_id')
    )
    op.create_table('active_deal',
    sa.Column('active_deal_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('from_company_completed', sa.Boolean(), nullable=False),
    sa.Column('to_company_completed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['deal_proposal.proposal_id'], ),
    sa.PrimaryKeyConstraint('active_deal_id')
    )
    # Add barter_coins with nullable first, set defaults, then make NOT NULL
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barter_coins', sa.Integer(), nullable=True))
    
    # Set default value for existing companies
    op.execute("UPDATE company SET barter_coins = 100 WHERE barter_coins IS NULL")
    
    # Make the column NOT NULL
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('barter_coins', nullable=False)

    # For service table, handle existing services similarly
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_hours', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Set defaults for existing services
    op.execute("UPDATE service SET duration_hours = 1.0 WHERE duration_hours IS NULL")
    op.execute("UPDATE service SET is_active = TRUE WHERE is_active IS NULL")
    
    # Make columns NOT NULL and drop old category column
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('duration_hours', nullable=False)
        batch_op.alter_column('is_active', nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_active')
        batch_op.drop_column('categories')
        batch_op.drop_column('duration_hours')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('barter_coins')

    op.drop_table('active_deal')
    op.drop_table('service_interest')
    op.drop_table('service_categories')
    op.drop_table('deal_proposal')
    # ### end Alembic commands ###
