"""admin overdragen

Revision ID: ee7149e880f0
Revises: 3e3f69f90526
Create Date: 2025-11-25 21:31:58.064758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee7149e880f0'
down_revision = '3e3f69f90526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('join_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('company_join_request',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('company_member',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('member_role', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('service',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('is_offered', sa.Boolean(), nullable=False),
    sa.Column('estimated_time_min', sa.Integer(), nullable=True),
    sa.Column('value_estimate', sa.Numeric(), nullable=True),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('barterdeal',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('service_a_id', sa.UUID(), nullable=False),
    sa.Column('service_b_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('ratio_a_to_b', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_a_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['service_b_id'], ['service.service_id'], ),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('contract',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('signed_by_initiator', sa.Boolean(), nullable=True),
    sa.Column('signed_by_counterparty', sa.Boolean(), nullable=True),
    sa.Column('signed_at_initiator', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at_counterparty', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['barterdeal.deal_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_table('review',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['barterdeal.deal_id'], ),
    sa.ForeignKeyConstraint(['reviewed_company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('contract')
    op.drop_table('barterdeal')
    op.drop_table('service')
    op.drop_table('company_member')
    op.drop_table('company_join_request')
    op.drop_table('user')
    op.drop_table('company')
    # ### end Alembic commands ###
