"""{wat je deed} - {je naam}

Revision ID: fbbf165fd90f
Revises: 37509ab8527d
Create Date: 2025-11-25 12:21:20.003156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbf165fd90f'
down_revision = '37509ab8527d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
